name: Publish Artifacts

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: chmod +x gradlew
      - run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/!(*-@(dev|sources|api)).jar
          github-files: build/libs/!(*-sources).jar
          version-type: release
          game-version-filter: releases
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip
